image: node:14

cache:
  paths:
  - node_modules/
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv docs public
  artifacts:
    paths:
    - public
  only:
  - master
