# .pre:
#   image: node:14
#   cache:
#     paths:
#     - node_modules/
#   pages:
#     stage: .pre
#     script:
#     - npm install
#     - npm run build
#     - rm -rf public
#     - mv dist public
#     artifacts:
#       paths:
#       - public
#     only:
#     - master
   

image: docker:19.03
variables:
  GIT_SSL_NO_VERIFY: "true"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
services:
  - docker:19.03-dind
  - node:14
stages:
  # - .pre
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.rsgitlab.mma.gov.br
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment Default --stack AppDev --service guia-de-estilo --rancher-url http://10.1.0.31:8080 --rancher-key AB9BFEEDC0550B93A0F9 --rancher-secret ZEbwj2qjnNyZ4ziDj25fPMw8rdj6KWSK1TKZL79q